DROP TABLE board_columns CASCADE;
DROP TABLE boards CASCADE;
DROP TABLE assignments CASCADE;
DROP TABLE boards_user_list CASCADE;
DROP TABLE cards CASCADE;
DROP TABLE cards_label_list CASCADE;
DROP TABLE labels CASCADE;
DROP TABLE users CASCADE;
