DROP TABLE board_columns CASCADE;
DROP TABLE boards CASCADE;
DROP TABLE assignments CASCADE;
DROP TABLE boards_invited_users CASCADE;
DROP TABLE cards CASCADE;
DROP TABLE cards_categories CASCADE;
DROP TABLE labels CASCADE;
DROP TABLE users CASCADE;